In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("EasyVisa.csv")
df.head(2)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified

In [5]:
df.shape

(25480, 12)

In [6]:
df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [7]:
data = df.to_dict(orient = "records")

In [8]:
len(data)

25480

In [9]:
DB_NAME = "US_Visa"
COLLECTION_NAME = "visa_data"
CONNECTION_URL = "mongodb+srv://vivechanas45_db:vivechanas45_db@cluster0.vdgpagh.mongodb.net/?appName=Cluster0"

In [10]:
import pymongo

In [11]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client [DB_NAME]
collection = data_base[COLLECTION_NAME]

# rec = collection.insert_many(data)

In [12]:
records = collection.find()
records

In [18]:
df1 = pd.DataFrame(list(records))
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified